-- Date 03/02/2020
-- Create table in database MySql

-- Command Create Table Treinador
CREATE TABLE TREINADOR (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
	IDADE INT(3) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
    ID_POKEMON1 INT(11),
	ID_POKEMON2 INT(11),
	ID_POKEMON3 INT(11),
	PRIMARY KEY (ID),
    FOREIGN KEY (ID_POKEMON1) REFERENCES POKEMON (ID),
    FOREIGN KEY (ID_POKEMON2) REFERENCES POKEMON (ID),
    FOREIGN KEY (ID_POKEMON3) REFERENCES POKEMON (ID)
);

-- Command Create Table Pokemon
CREATE TABLE POKEMON (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	ALTURA FLOAT(2) NOT NULL,
	PESO FLOAT(2) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	HABILIDADE VARCHAR(100) NOT NULL,
    HABILIDADE2 VARCHAR(100),
    TIPO VARCHAR(50) NOT NULL,
    FRAQUEZA VARCHAR(50) NOT NULL,
    FRAQUEZA2 VARCHAR(50),
    DESCRICAO VARCHAR(255),
	PRIMARY KEY (ID)
);