-- Date 03/02/2020
-- Create table in database MySql

-- Command Create Table Treinador
CREATE TABLE TREINADOR (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
	IDADE INT(3) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
    ID_POKEMON INT(11),
	PRIMARY KEY (ID),
    FOREIGN KEY (ID_POKEMON) REFERENCES POKEMON (ID)
);

-- Command Create Table Pokemon
CREATE TABLE POKEMON (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
	ALTURA FLOAT(2) NOT NULL,
	PESO FLOAT(2) NOT NULL,
	CATEGORIA VARCHAR(50) NOT NULL,
	HABILIDADE VARCHAR(100) NOT NULL,
    HABILIDADE2 VARCHAR(100),
    FRAQUEZA VARCHAR(50) NOT NULL,
    FRAQUEZA2 VARCHAR(50),
    DESCRICAO VARCHAR(255),
	PRIMARY KEY (ID)
);
