-- Tabela da Api produtos 'nao testada'

CREATE TABLE PRODUTO (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    MARCA VARCHAR(100) NOT NULL,
    QUANTIDADE INT(11) NOT NULL,
    VALOR FLOAT(2) NOT NULL,
    VALIDADE DATE,
    PRIMARY KEY (ID)
);